### PR TITLE
fixing uuid for InfrastructureModels

### PR DESCRIPTION
**Pull request by timkittel**
Hi all,
I wanted to test out PowerSimulations.jl but the installation fails due to the InfrastructureModels.jl dependency. Even after manual installation of this package, I still cannot install PowerSimulations.jl. 
It seems, there is a mistake in the uuid for InfrastructureModels.jl if you compare the [registry](https://github.com/JuliaRegistries/General/blob/88bd2d6e6dfc9a9948879a671afc6cbd6849244a/I/InfrastructureModels/Package.toml#L2) with your [`Project.toml`](https://github.com/NREL/PowerSimulations.jl/blob/10ae99136a9d7813d3467a55de12f18058bce022/Project.toml#L12).

This is a PR fixing the uuid. Could you check whether you agree?

### CODE REVIEW

**Comment by timkittel** [comment]
cc @sabineauer

**Comment by claytonpbarrows** [comment]
@timkittel thank you.

**Comment by claytonpbarrows** [comment]
@timkittel thanks!

**Comment by timkittel** [comment]
Great, the installation via `dev` works now!

**Pull request merged**
